name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Lock file
      run: uv lock

    - name: Install the project
      run: uv sync --locked --all-extras --dev

    - name: Build
      run: make build

    - name: Publish
      run: uv publish -t ${{ secrets.PYPI_RELEASE_TOKEN }}